### ISSUE TITLE
Enums with custom types

### ISSUE THREAD

**Issue by RandyMarsh1** [Wulf/tsync#25]
Is it possible to have Enum variants that take a self named struct parameter and output as types?

```
#[tsync]
enum Message {
    MyStruct1(MyStruct1),
    MyStruct2(MyStruct2),
}
```
The ideal output:  `type Message = | MyStruct1 | MyStruct2;` where the structs are types, not strings

.

This would allow easy structuring of JSON in Rust and Destructing in TypeScript, Example:
```
#[tsync]
#[derive(Serialize)]
struct MyStruct1 {
    data1: bool,
    data2: MyStruct2,
}

#[tsync]
#[derive(Serialize)]
struct MyStruct2 {
    data1: String,
    data2: i32,
}

#[tsync]
#[derive(Serialize)]
enum Message {
    MyStruct1(MyStruct1),
    MyStruct2(MyStruct2),
}

fn main() {
    let message = Message::MyStruct2(MyStruct2 {
        data1: "hello".to_string(),
        data2: 42,
    });

    let json = serde_json::to_string(&message).unwrap();
    println!("Send to frontend: {}", json);
    // Output: {"MyStruct2":{"data1":"hello","data2":42}}
}

```

**Comment by Wulf** [comment]
hey @RandyMarsh1, thanks for reporting this :) 

Let me know if 1.7.0 doesn't work for you. I think eventually what we'll want to do is namespace a lot of this output. Closing this for now, feel free to re-open it

**Comment by RandyMarsh1** [comment]
Thanks, nested structs within structs now works, this is a great improvement 👍

However the specific scenario I was hoping for was Rust Enums that take a struct of the same name as input parameter like this:
```
#[tsync]
#[derive(Serialize)]
enum Message {
    MyStruct1(MyStruct1), <-- enum variant name == struct name
    MyStruct2(MyStruct2),
}
```
This currently does not output anything and is skipped.

The following does output a type but the variants are Strings, not Interfaces.
```
#[tsync]
#[derive(Serialize)]
enum Message2 {
    MyStruct1,
    MyStruct2,
}
```
This admittable requires a somewhat opinionated structure but I think a nice clean way of generating JSON with the Enum variant as key and Struct as Value. The Example code in original post should compile and demonstrates the use case.

**Comment by Wulf** [comment]
Ah that should be possible too -- do you mind lending me a hand with this one?

* Update `fn make_externally_tagged_variant(..)` [here](https://github.com/Wulf/tsync/blob/main/src/to_typescript/enums.rs#L236) to output the type separately and use the identifier, similar to the approach used in #26.
* Run [`./test/enum/tsync.sh`](https://github.com/Wulf/tsync/blob/main/test/enum/tsync.sh) and see if the [`./test/enum/typescript.d.ts`](https://github.com/Wulf/tsync/blob/main/test/enum/typescript.d.ts) file changes appropriately
