### ISSUE TITLE
[feature request] Support serde flatten

### ISSUE THREAD

**Issue by rlcurrall** [Wulf/tsync#48]
Currently the serde flatten attribute is not supported. It would be nice to have this code:

```rust
#[tsync]
#[derive(Serialize)]
struct Outter {
    id: String,
    #[serde(flatten)]
    inner: Inner,
}

#[tsync]
#[derive(Serialize)]
struct Inner {
    value: String,
}
```

generate something like this:
```ts
type Outter = Inner & {
  id: string;
}

interface Inner {
  value: string;
}
```

Also, enum support would be ideal. I'm open to other options for how the outputted TS would look, I'm only suggesting the intersection type because it would be easier for it to work with enums since they are usually defined with the `type` keyword.

**Comment by Wulf** [comment]
Hey @rlcurrall, thanks for this :)

Does the TS output resemble how serde serializes the object exactly?

**Comment by rlcurrall** [comment]
@Wulf, sorry for the delay in response!

I've created some examples to show what the functionality, but here's an example with an nested struct being flattened:

- [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=63bb7e33e0a6cd6851c7fb9e9d211756)
- [TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8grsYEBOUC8UCSA7bKoBkUA3gFBRQCWAJgFxQDOwyl2A5gNykC+pprSZADMAhgGNoOPKjIUAbiIA2cCPSYt2XXqTEB7bEyhIm9eInwZZFKnSgAiAIwAmAMwAWOwBpy1hctX2IgzUQl48XEA) (select errors tab to see no errors)

I think nested enums are a bit more interesting when flattened as you can see here:

- [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=125591bc5648f0af267de1826fdc7a44)
- [TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCALAhmGwpwC8cA3gL4BQFoksCyqAQhBANZFzNsAqDcAZKQpw4AOywBbYAC44AZxhQAlqIDmAbmFwAxtlz45sgIJQoWRAB5MOPFAB8mkQFc5+APpRgANyXAA7nIA-Mam5hYKymoOFJTU4NDwSCicLKy8yYRaAD4pPAxubgBiStowShCi2blp+W4AchXFpeWimhRJTKnpwAVNZRUcJFodsgBEfS2jjnCqwKKeshEqGjGaHdXdBQ2iEwPEQyIjcKPbu6JTWnJOAEYAVsCli4rLmmRt2hUKCMAKslzs+y0InEUjGRjgAHUlAAvLBQAAmcAgADM4ABROEwDCuLCjAA0QJ0elshjgAG0ALoEkSHBhjM74wmzeYyY7IrCiGBYOSIUarChAA)

One thing to note is that serde allows for you to flatten a record that has overlapping keys [as you can see here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2d8e51a3ef3ec5d1893db40bdeed79ea). Not sure if we should, or even care to handle this case differently than serde, but something to note.

**Comment by Wulf** [comment]
hey @rlcurrall really sorry to have left this hanging.

Thanks for the examples -- they helped clarify the functionality.

:rocket: I'll merge in your PR and cut a release :)
