### ISSUE TITLE
Feature Request: Supporting `const` scalars such as numbers and strings + enums (?)

### ISSUE THREAD

**Issue by AravindPrabhs** [Wulf/tsync#5]
Hi,

Thanks for the great work!

Would you be interested in adding conversion for `const` Items that are of a simple type into Typescript statements like a string, number and maybe a serde_json::Value where the RHS has to `json!` invocation ? This overall would make writing my tests easier with fully typed data-attributes and increase general ergonomics.

```
const SOME_FLAG: u32 = 0; ---> const SOME_FLAG = 0;
const SOME_JSON: serde_json::Value = serde_json::json!({
        "name": "John Doe",
        "age": 43,
        "phones": [
            "+44 1234567",
            "+44 2345678"
        ]
    })
--->
const SOME_JSON = {
        "name": "John Doe",
        "age": 43,
        "phones": [
            "+44 1234567",
            "+44 2345678"
        ]
    }; 
```

Enums/Variants would also be great however I would be unsure of what would be best I was thinking something like:
```rust
#[tsync(Case::ScreamingSnake)]
enum EnumType {
    CaseOne
    CaseTwo(i32),
    CaseThree {
        x: i64,
        y: i64
    }
}
``` goes to
```typescript
type EnumType = "CaseOne" | [number] | { type: "CaseThree", x: number, y: number }
```
I don't usually end up mixing tuple and named structs in enums so unsure of the best way to preserve "CaseTwo":
```typescript
type EnumType = "CaseOne" | ["CaseTwo", number] | { type: "CaseThree", x: number, y: number }
``` 
or just convert to dictionary and probably the better way.
```typescript
type EnumType = "CaseOne" | { type: "CaseTwo", 0: number} | { type: "CaseThree", x: number, y: number }
``` 

Very happy to take a crack at both in a PR. Let me know your thoughts!

**Comment by Wulf** [comment]
Hi @AravindPrabhs, this looks like a great feature to add :)

Regarding enums — I’m okay with whatever you decide to support as long as serde_json can [deserialize it back into Rust](https://serde.rs/enum-representations.html). Also, could we leave out the #[tsync] attribute parameter change for now? If you really need something like that, let’s discuss it in detail in another issue — the only reason being, I’ve yet to think about parameters for the attribute and I think there are a lot more use cases we need to consider. 

Regardless, thanks for suggesting this and thinking about the edge cases here :)

**Comment by Wulf** [comment]
@AravindPrabhs thanks for your patience with this one; I've been sick all week. I've added some documentation on the `README.md` and released 1.6.0 now.

![image](https://user-images.githubusercontent.com/4259838/202921777-5f1ccb39-f3c5-4208-877b-dc27327f1806.png)

**Comment by Wulf** [comment]
I hope all is well on your end :)

**Comment by AravindPrabhs** [comment]
@Wulf no worries at all, those docs are clear and look good.

Thanks for the work (and project) 💯
