### ISSUE TITLE
Support for const enums

### ISSUE THREAD

**Issue by pendruct** [Wulf/tsync#50]
Hi, is there any way to do const enums?

For example,

```rust
enum Test {
  Foo,
  Bar
}
```

becomes

```typescript
const enum Test {
  Foo,
  Bar
}
```

or..

```rust
enum Test {
  Foo = 5,
  Bar = 6
}
```

becomes 

```typescript
const enum Test {
  Foo = 5,
  Bar = 6
}
```

Currently it seems like the enums generated do not have the const prefix in the generated Typescript code. I only use const enums for my project

**Comment by AnthonyMichaelTDM** [comment]
^ this should work

**Comment by pendruct** [comment]
Wow, thanks so much! @AnthonyMichaelTDM Did you do all that just for me? That's so kind!

**Comment by AnthonyMichaelTDM** [comment]
🫡
