### ISSUE TITLE
tsync from other proc-macros?

### ISSUE THREAD

**Issue by RossRogers** [Wulf/tsync#8]
If a proc-macro generates a struct, those generated structs are not exported, even if the `#[tsync]` annotation is on the generated struct.  Is this possible to somehow accomplish with tsync's current architecture?

**Comment by Wulf** [comment]
No, not with the current architecture. Maybe in the future though :)

**Comment by AravindPrabhs** [comment]
I also ran into this. I was able to cobble a hacky solution:
 - change the tsync-macro to add a comment "tsync managed"
 - use cargo expand to expand the file in question (doing the whole crate gets massive with all web/serialization expansion) 
 - edit `has_tsync_attribute` to also check for the doc comments so those constructs are also considered.

The "search" for "tsync" attributes has to be changed to be changed to recursed on modules and in my case impls as well.

**Comment by Wulf** [comment]
Closing this; feel free to re-open!
